apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: gateway-demo
data:
  datasources.yml: |
    apiVersion: 1

    datasources:

      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: false
        jsonData:
          httpMethod: POST
          exemplarTraceIdDestinations:
            - name: traceId
              datasourceUid: tempo

      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        editable: false
        jsonData:
          derivedFields:
            - matcherRegex: "traceId=(\\w+)"
              name: TraceId
              url: "$${__value.raw}"
              datasourceUid: tempo
              urlDisplayLabel: "View Trace in Tempo"

      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        uid: tempo
        editable: false
        jsonData:
          httpMethod: GET
          serviceMap:
            datasourceUid: prometheus
          nodeGraph:
            enabled: true
          tracesToLogsV2:
            datasourceUid: loki
            spanStartTimeShift: "-1m"
            spanEndTimeShift: "1m"
            filterByTraceID: true
            customQuery: true
            query: '{app=~"api-gateway|booking-service"} |= "$${__trace.traceId}"'

  dashboards.yml: |
    apiVersion: 1

    providers:
      - name: Gateway Reference Dashboards
        orgId: 1
        type: file
        disableDeletion: false
        updateIntervalSeconds: 30
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: false
