apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: gateway-demo
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_timeout: 10s

    scrape_configs:
      - job_name: otel-collector
        static_configs:
          - targets: ['otel-collector:8889']

      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']

      - job_name: edge-service
        metrics_path: /actuator/prometheus
        scrape_interval: 15s
        static_configs:
          - targets: ['edge-service:8080']
            labels:
              application: edge-service
              environment: local

      - job_name: booking-service
        metrics_path: /actuator/prometheus
        scrape_interval: 15s
        static_configs:
          - targets: ['booking-service:9001']
            labels:
              application: booking-service
              environment: local
