apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: gateway-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: booking-service:latest
          imagePullPolicy: Never   # use locally built image
          ports:
            - containerPort: 9001
          envFrom:
            - configMapRef:
                name: booking-service-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9001
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9001
            initialDelaySeconds: 90
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: gateway-demo
spec:
  selector:
    app: booking-service
  ports:
    - port: 9001
      targetPort: 9001
  type: ClusterIP  # internal only — accessed via edge-service
