apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
  namespace: gateway-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edge-service
  template:
    metadata:
      labels:
        app: edge-service
    spec:
      containers:
        - name: edge-service
          image: edge-service:latest
          imagePullPolicy: Never   # use locally built image
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: edge-service-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 15
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: edge-service
  namespace: gateway-demo
spec:
  selector:
    app: edge-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort  # accessible at localhost:30080
