apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: gateway-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.4.3
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GF_SECURITY_ADMIN_USER
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GF_SECURITY_ADMIN_PASSWORD
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 15
          volumeMounts:
            - name: grafana-provisioning-datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
            - name: grafana-provisioning-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
              readOnly: true

      volumes:
        - name: grafana-provisioning-datasources
          configMap:
            name: grafana-provisioning
            items:
              - key: datasources.yml
                path: datasources.yml

        - name: grafana-provisioning-dashboards
          configMap:
            name: grafana-provisioning
            items:
              - key: dashboards.yml
                path: dashboards.yml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: gateway-demo
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: gateway-demo
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
  type: NodePort  # accessible at localhost:30001
